spring:
  profiles: test
  application:
    name: spring-boot-family

server:
  port: 8088

spring.datasource.family:
  url: jdbc:mysql://127.0.0.1:3306/demo
  username: root
  password:
  driver-class-name: com.mysql.jdbc.Driver

keycloak:
  configurationFile: "classpath:keycloak.json"


#logging:
#  level:
#    org: DEBUG
